import type { Metadata } from "next";
import { Map } from "@components/Map";
import { ToastContainer } from "react-toastify";
import { PassengerRealtimeBridge } from "@context/PassengerRealtimeContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function MapLayout({
	children,
}: Readonly<{
    children: React.ReactNode;
}>) {
	return (
    	<>
			<PassengerRealtimeBridge>
				<ToastContainer />
				{children}
				<Map />
			</PassengerRealtimeBridge>
		</>
	);
}